# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flix_codePath' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for flix_codePath
  pod 'AlamofireImage'

  target 'flix_codePathTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'flix_codePathUITests' do
    # Pods for testing
  end

end
